module.exports = {
  rules: {
    'array-bracket-spacing': [2, 'never'],
    'block-spacing': [2, 'always'],
    'brace-style': [2, '1tbs', { allowSingleLine: true }],
    camelcase: [2, { properties: 'never' }],
    'comma-dangle': [2, 'always-multiline'],
    'comma-spacing': [2, {
      before: false,
      after: true,
    }],
    'comma-style': [2, 'last'],
    'computed-property-spacing': [2, 'never'],
    'consistent-this': 0,
    'eol-last': 2,
    'func-names': 0,
    'func-style': 0,
    'id-blacklist': 0,
    'id-length': 0,
    'id-match': 0,
    indent: [2, 2, { SwitchCase: 1 }],
    'jsx-quotes': [2, 'prefer-double'],
    'key-spacing': [2, {
      beforeColon: false,
      afterColon: true,
    }],
    'keyword-spacing': [2, {
      before: true,
      after: true,
      overrides: {},
    }],
    'linebreak-style': 0,
    'lines-around-comment': 0,
    'max-depth': [2, 4],
    'max-len': [2, 100, 2, {
      ignoreUrls: true,
      ignoreComments: false,
      ignoreTrailingComments: true,
    }],
    'max-lines': 0,
    'max-nested-callbacks': 0,
    'max-params': 0,
    'max-statements': 0,
    'new-cap': [2, {
      newIsCap: true,
      capIsNew: false,
    }],
    'new-parens': 2,
    'newline-after-var': 0,
    'newline-before-return': 0,
    'newline-per-chained-call': [2, { ignoreChainWithDepth: 2 }],
    'no-array-constructor': 2,
    'no-bitwise': 0,
    'no-continue': 0,
    'no-inline-comments': 0,
    'no-lonely-if': 0,
    'no-mixed-operators': 0,
    'no-mixed-spaces-and-tabs': 2,
    'no-multiple-empty-lines': [2, { max: 1 }],
    'no-negated-condition': 2,
    'no-nested-ternary': 1,
    'no-new-object': 2,
    'no-plusplus': 0,
    'no-restricted-syntax': 0,
    'no-spaced-func': 2,
    'no-ternary': 0,
    'no-trailing-spaces': 2,
    'no-underscore-dangle': 0,
    'no-unneeded-ternary': [2, { defaultAssignment: false }],
    'no-whitespace-before-property': 2,
    'object-curly-newline': 0,
    'object-curly-spacing': [2, 'always'],
    'object-property-newline': 2,
    'one-var': [2, { initialized: 'never' }],
    'one-var-declaration-per-line': [2, 'always'],
    'operator-assignment': 0,
    'operator-linebreak': [2, 'after', {
      overrides: {
        '?': 'before',
        ':': 'before',
      },
    }],
    'padded-blocks': [2, 'never'],
    'quote-props': [2, 'as-needed', {
      keywords: false,
      unnecessary: true,
      numbers: false,
    }],
    quotes: [2, 'single', 'avoid-escape'],
    'require-jsdoc': 0,
    semi: [2, 'never'],
    'semi-spacing': [2, {
      before: false,
      after: true,
    }],
    'sort-vars': 0,
    'space-before-blocks': [2, 'always'],
    'space-before-function-paren': [2, 'always'],
    'space-in-parens': [2, 'never'],
    'space-infix-ops': 2,
    'space-unary-ops': [2, {
      words: true,
      nonwords: false,
    }],
    'spaced-comment': [2, 'always', {
      markers: ['global', 'globals', 'eslint', 'eslint-disable', '*package', '!', ','],
    }],
    'unicode-bom': 0,
    'wrap-regex': 0,
  },
}
